dist: trusty

notifications:
  email: false

branches:
  only:
    - master
    - /^\d\.\d$/

jobs:
  include:
    - stage: Unit tests
      language: php
      php: 7.2
    - stage: Code quality
      language: generic
      services:
        - docker
      before_install:
        - docker pull jakzal/phpqa
      script:
        - docker ps

script:
  - echo SCRIPT

cache:
  directories:
    - $HOME/.composer/cache
    - var/cache
