notifications:
  email: false

language: php

php:
  - 7.1
  - 7.2

env:
  global:
    - COMPOSER_ARGS="--no-progress --prefer-dist --no-interaction --no-suggest"
    - PHPUNIT_ARGS=""

matrix:
  include:
    - php: 7.1
      env:
        - DEPS=high
        - CC=true
        - CS=true
        - SA=true
        - SMOKE_TEST=true
    - php: 7.2
      env:
        - DEPS=low
  fast_finish: true

before_script:
  - if [[ $CC != true ]] ; then phpenv config-rm xdebug.ini || true ; fi
  - if [[ $CS = true ]] ; then mkdir -p var/cache ; fi
  - travis_retry composer self-update

before_install:
  - source .travis/tfold

install:
  - travis_retry php .travis/packager.php HEAD^ $(find src/*/composer.json -type f -printf '%h\n')
  - if [[ ! $DEPS || $DEPS = high ]] ; then travis_retry bin/composer update $COMPOSER_ARGS ; fi
  - if [[ $DEPS = low ]] ; then travis_retry bin/composer update $COMPOSER_ARGS --prefer-stable --prefer-lowest ; fi
  - bin/phpunit install
  - if [[ $CS = true || $SA = true ]] ; then composer install $COMPOSER_ARGS ; fi

script:
  - if [[ ! $CC  ]] ; then bin/phpunit $PHPUNIT_ARGS ; fi
  - if [[ $CC = true ]] ; then bin/phpunit --coverage-clover=coverage.xml $PHPUNIT_ARGS ; fi
  - if [[ $CS = true ]] ; then bin/cs ; fi
  - if [[ $SA = true ]] ; then bin/sa ; fi
  - if [[ $SMOKE_TEST = true ]] ; then bin/smoke-test-bundles ; fi

after_success:
  - if [[ $CC = true ]] ; then .travis/codecov ; fi

cache:
  directories:
    - $HOME/.composer/cache/files/
    - var/

branches:
  only:
    - master
    - /^\d\.\d$/
