dist: trusty
language: php

notifications:
  email: false

branches:
  only:
    - master
    - /^\d\.\d$/

php: 7.2

jobs:
  include:
    - stage: Unit tests
    - stage: Code quality
      services:
        - docker
      before_install:
        - docker pull jakzal/phpqa
      script:
        - docker ps

script:
  - echo SCRIPT

cache:
  directories:
    - $HOME/.composer/cache
    - var/cache
