notifications:
  email: false

language: php

php:
  - 7.1
  - 7.2
  - nightly

env:
  global:
    - COMPOSER_ARGS="--prefer-dist --no-interaction --no-suggest"
    - PHPUNIT_ARGS=""

matrix:
  include:
    - php: 7.1
      env:
        - DEPS=low
    - php: 7.1
      env:
        - DEPS=high
        - CC=true
        - CS=true
        - SA=true
    - php: 7.2
      env:
        - DEPS=low
    - php: 7.2
      env:
        - DEPS=high

allow_failures:
- php:
    - nightly

fast_finish: true

before_script:
  - travis_retry composer self-update

before_install:
  - .travis/tfold

install:
  - if [[ ! $DEPS  ]] ; then travis_retry bin/composer install $COMPOSER_ARGS ; fi
  - if [[ $DEPS = high ]] ; then travis_retry bin/composer update $COMPOSER_ARGS --prefer-stable ; fi
  - if [[ $DEPS = low ]] ; then travis_retry bin/composer update $COMPOSER_ARGS --prefer-stable --prefer-lowest ; fi
  - bin/phpunit install
  - if [[ $CS = true ]] || [[ $SA = true ]] ; then composer install ; fi

script:
  - if [[ ! $CC  ]] ; then bin/phpunit $PHPUNIT_ARGS ; fi
  - if [[ $CC = true ]] ; then bin/phpunit --coverage-clover=coverage.xml $PHPUNIT_ARGS ; fi
  - if [[ $CS = true ]] ; then bin/cs ; fi
  - if [[ $SA = true ]] ; then bin/sa ; fi

after_success:
  - if [[ $CC = true ]] ; then  .travis/codecov ; fi

cache:
  directories:
    - $HOME/.composer/cache/files/
