dist: trusty
language: php

notifications:
  email: false

branches:
  only:
    - master
    - /^\d\.\d$/

php: 7.2

services:
  - docker

before_install:
  - docker pull jakzal/phpqa

script:
  - docker ps

cache:
  directories:
    - $HOME/.composer/cache
    - var/cache
