language: php

php:
  - 7.1
  - 7.2
  - nightly

env:
  global:
    - COMPOSER_ARGS="--prefer-dist --no-interaction --no-suggest"

matrix:
  include:
    - php: 7.1
      env:
        - DEPS=low
        - CS=true
    - php: 7.1
      env:
        - DEPS=high
        - CS=true
    - php: 7.2
      env:
        - DEPS=low
        - CS=true
    - php: 7.2
      env:
        - DEPS=high
        - CS=true

allow_failures:
- php:
    - nightly

fast_finish: true

before_script:
  - travis_retry composer self-update

install:
  - if [[ ! $DEPS  ]] ; then travis_retry bin/composer install $COMPOSER_ARGS ; fi
  - if [[ $DEPS = high ]] ; then travis_retry bin/composer update $COMPOSER_ARGS --prefer-stable ; fi
  - if [[ $DEPS = low ]] ; then travis_retry bin/composer update $COMPOSER_ARGS --prefer-stable --prefer-lowest ; fi
  - bin/phpunit install
  - if [[ $CS = true ]] ; then composer install --working-dir=.travis ; fi

script:
  - bin/phpunit --coverage-clover=coverage.xml
  - if [[ $CS = true ]] ; then .travis/vendor/bin/php-cs-fixer fix --dry-run --verbose --diff src/ ; fi

after_success:
  - .travis/codecov

cache:
  directories:
    - $HOME/.composer/cache/files/
