site_name: MsgPHP Documentation
site_description: Message based domain layers. Shipped with industry standard infrastructure.
repo_url: https://github.com/msgphp/msgphp
edit_uri: blob/master/docs/
site_dir: var/docs/build/

theme:
    name: material
    custom_dir: docs/.theme
extra_css: [style.css]

markdown_extensions:
    - codehilite

pages:
- Home: index.md
- Code conventions: code-conventions.md
- Domain-driven-design:
    - Identifiers: ddd/identifiers.md
    - Identities: ddd/identities.md
    - Identity mapping: ddd/identity-mapping.md
    - Collections: ddd/collections.md
    - Factories:
        - Object factory: ddd/factory/object.md
        - Entity aware factory: ddd/factory/entity-aware.md
        - Static factory: ddd/factory/static.md
    - Repositories: ddd/repositories.md
    - Entities: ddd/entities.md
- Event sourcing:
    - Events: event-sourcing/events.md
    - Event handlers: event-sourcing/event-handlers.md
- Message driven:
    - Message bus: message-driven/message-bus.md
    - Message dispatcher: message-driven/message-dispatcher.md
    - CQRS: message-driven/cqrs.md
- Infrastructure:
    - UUID: infrastructure/uuid.md
    - Doctrine Collections: infrastructure/doctrine-collections.md
    - Doctrine DBAL: infrastructure/doctrine-dbal.md
    - Doctrine ORM: infrastructure/doctrine-orm.md
    - Symfony Console: infrastructure/symfony-console.md
- Cookbook:
    - Bundle installation: cookbook/bundle-installation.md
