site_name: MsgPHP Documentation
site_description: Reusable domain layers. Shipped with industry standard infrastructure.
repo_url: https://github.com/msgphp/msgphp
edit_uri: blob/master/docs/

theme:
    name: material
    custom_dir: docs/.theme
extra_css: [style.css]
markdown_extensions:
    - codehilite
    - admonition
    - toc:
          permalink: true

nav:
    - Home: index.md
    - Symfony Cookbook:
          - User Bundle:
                - Installation: cookbook/user-bundle/installation.md
                - Creating a User: cookbook/user-bundle/creating-a-user.md
          - Configuring Symfony Messenger: cookbook/configuring-symfony-messenger.md
          - Configuring Doctrine ORM: cookbook/configuring-doctrine-orm.md
    - Domain Driven Design:
          - Identifiers: ddd/identifiers.md
          - Collections: ddd/collections.md
          - Entities: ddd/entities.md
          - Repositories: ddd/repositories.md
          - Object Factory: ddd/object-factory.md
          - Message Bus: ddd/message-bus.md
    - Event Sourcing:
          - Event Handlers: event-sourcing/event-handlers.md
          - Events: event-sourcing/events.md
    - Projection:
          - Models: projection/models.md
          - Document Transformers: projection/document-transformers.md
          - Type Registry: projection/type-registry.md
          - Repositories: projection/repositories.md
          - Synchronization: projection/synchronization.md
    - Infrastructure:
          - Doctrine Collections: infrastructure/doctrine-collections.md
          - Doctrine DBAL: infrastructure/doctrine-dbal.md
          - Doctrine ORM: infrastructure/doctrine-orm.md
          - Elasticsearch: infrastructure/elasticsearch.md
          - Symfony Console: infrastructure/symfony-console.md
          - Symfony Messenger: infrastructure/symfony-messenger.md
          - UUID: infrastructure/uuid.md
