site_name: MsgPHP Documentation
site_description: Message based domain layers. Shipped with industry standard infrastructure.
repo_url: https://github.com/msgphp/msgphp
edit_uri: blob/master/docs/
site_dir: var/docs/build/

theme:
    name: 'material'
extra_css: [style.css]
markdown_extensions:
    - codehilite

pages:
- Home: index.md
- Code conventions: code_conventions.md
- Domain-driven-design:
    - Identifiers: ddd/identifiers.md
    - Identity mapping: ddd/identity_mapping.md
    - Collections: ddd/collections.md
    - Factories:
        - Object factories: ddd/object_factories.md
        - Entity factories: ddd/entity_factories.md
        - Static factories: ddd/static_factories.md
    - Repositories: ddd/repositories.md
